# The pod can be scheduled on nodes with the taint "gpu=true:NoSchedule" and as long as there is at 
# least one Pod within Zone V already labeled with tier=stg and preferably the pods has a label env=dev.
# even If a pod doesn't the label env=dev, the scheduler still schedules the Pod.
# conditon: (gpu=true:NoSchedule) AND ((tier=stg --> zone A [must satify]) OR (env=dev --> zone A))
apiVersion: v1
kind: Pod
metadata: 
  name: toleration-pa
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: tier
            operator: In
            values:
            - stg
        topologyKey: topology.kubernetes.io/zone
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 5
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: env
              operator: In
              values:
              - dev
          topologyKey: topology.kubernetes.io/zone
  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx